export default {
  extName: 'Live Earnings Counter - Millisecond-Level Salary Tracking',
  extDescription: 'Track your salary in real-time with millisecond precision. Watch earnings grow every second you work!',
  header_title: 'Real-time Salary Tracker',
  salary_monthly_label: 'Monthly Salary',
  salary_monthly_placeholder: 'Enter monthly salary',
  salary_currency_label: 'Currency Unit',
  salary_currency_placeholder: '¥',
  salary_currency_hint: 'Can be set to points, stars, etc. to protect privacy',
  salary_workdays_label: 'Work Days',
  salary_workdays_monday: 'Mon',
  salary_workdays_tuesday: 'Tue',
  salary_workdays_wednesday: 'Wed',
  salary_workdays_thursday: 'Thu',
  salary_workdays_friday: 'Fri',
  salary_workdays_saturday: 'Sat',
  salary_workdays_sunday: 'Sun',
  salary_workTime_start: 'Work Start Time',
  salary_workTime_end: 'Work End Time',
  salary_updateInterval_label: 'Update Interval (ms)',
  salary_updateInterval_hint: 'Range: 100-5000ms, Step: 100ms',
  display_nonWorkingDay: 'Non-working Day',
  display_workStatus_worked: 'Worked Today',
  display_workStatus_hourlyRate: 'Per Hour',
  display_workStatus_workDaysInMonth: 'Working Days This Month',
  display_timeUnit_hour: 'hour',
  display_timeUnit_minute: 'minute',
  content_salary_rest: 'Rest',
  content_tooltip_worked: 'Worked: $1',
  content_tooltip_hourly_rate: 'Hourly Rate: $1',
  content_tooltip_work_days: 'Working Days This Month: $1',
  content_tooltip_non_working: 'Non-working Day',
  content_progress_full: '▮',
  content_progress_empty: '▯',
};
